version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version
  pre_build:
    commands:
      - echo Skipping Docker login (no credentials provided)
  build:
    commands:
      - echo Building, Testing and packaging the application...
      - cd path/to/your/project/directory  # Change this to the correct path where your pom.xml is located
      - mvn package
  post_build:
    commands:
      - echo Build, Testing and packaging completed.
artifacts:
  files:
    - target/*.jar
